### ISSUE TITLE
Idee: snake spielen

### ISSUE THREAD

**Issue by cboltz** [casartar/MacherDaachBadgeFirmware#3]
siehe z. B. https://www.instructables.com/id/8x8-Matrix-Snake-Game/ - oder einfach "snake 8x8" googlen ;-)

**Comment by schmofu** [comment]
Auf jeden Fall. Machst Du das selbst oder soll ich das übernehmen?

**Comment by cboltz** [comment]
Mach Du das bitte - ich habe schon mehr als genug auf meiner TODO-Liste ;-)
